name: Push to Swell

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.1'

      - name: Install dependencies and push to Swell
        run: |
          npm i -g @swell/cli@latest
          npm ci
          swell app push --force
